version: "3.5"
services:
  clickhouse:
    build:
      context: ./build
    networks:
        zabbix:
            aliases:
            - ch-server
    ports:
        - "8123:8123"
        - "9000:9000" 
    volumes:
        - data:/var/lib/clickhouse
    ulimits:
        nproc: 65535
        nofile:
            soft: 262144
            hard: 262144
networks:
  zabbix:
    external:
      name: zabbix 

volumes:
  data: