version: "3.5"
services:
  mysql:
    build:
      context: ./mysql/build
    env_file:
    - .env
    entrypoint: ['bash', 'docker-entrypoint.sh', '--default-authentication-plugin=mysql_native_password', '--character-set-server=utf8', '--collation-server=utf8_bin']
    networks:
      zabbix:
        aliases:
        - mysql-server
    ports:
    - "3306:3306" 
    volumes:
    - data_mysql:/var/lib/mysql

  clickhouse:
    build:
      context: ./clickhouse/build
    env_file:
    - .env
    networks:
      zabbix:
        aliases:
        - ch-server
    ports:
    - "8123:8123"
    - "9000:9000"
    volumes:
     - data_clickhouse:/var/lib/clickhouse
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144

  glaber-nginx:
    build:
      context: ./glaber-nginx/build
    networks:
      zabbix:
        aliases:
        - glaber-nginx
    ports:
    - "8050:80" 
    env_file:
    - .env

  glaber-server:
    build:
      context: ./glaber-server/build
    env_file:
    - .env
    ports:
      - "10051"
    networks:
      zabbix:
        aliases:
        - zabbix
networks:
  zabbix:

volumes:
  data_mysql:
  data_clickhouse: