version: "3.5"
services:
  zabbix-mysql:
    build:
      context: ./mysql/build
    env_file:
    - .env
    networks:
      zabbix:
        aliases:
        - mysql-server
    ports:
    - "3306:3306" 
    volumes:
    - data_mysql:/var/lib/mysql
  clickhouse:
    build:
      context: ./clickhouse/build
    env_file:
    - .env
    networks:
      zabbix:
        aliases:
        - ch-server
    ports:
    - "8123"
    - "9000" 
    volumes:
    - data_clickhouse:/var/lib/clickhouse
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
  glaber-nginx:
    build:
      context: ./glaber-nginx
    networks:
      zabbix:
        aliases:
        - glaber-nginx
    ports:
    - "8050:80" 
    env_file:
    - .env
  glaber-server:
    build:
      context: ./glaber-server
    env_file:
    - .env
    ports:
    - "10051"
    networks:
      zabbix:
        aliases:
        - glaber-server-1
networks:
  zabbix:

volumes:
  data_mysql:
  data_clickhouse: