version: "3.5"
services:
  zbx-srv-1:
    build:
      context: ./zabbix-server/build
    env_file:
      - common.env
      - zbx.env
    environment:
      ZBX_SERVER_NAME: zabbix-1
      ZBX_SERVER_ID: 1
    ports:
      - "10051"
    networks:
      zabbix:
        aliases:
          - zabbix-1
  zbx-srv-2:
      build:
        context: ./zabbix-server/build
      env_file:
        - common.env
        - zbx.env
      environment:
        ZBX_SERVER_NAME: zabbix-2
        ZBX_SERVER_ID: 2
      ports:
        - "10051"   
      networks:
        zabbix:
          aliases:
            - zabbix-2
  zbx-srv-3:
      build:
        context: ./zabbix-server/build
      env_file:
        - common.env
        - zbx.env
      environment:
        ZBX_SERVER_NAME: zabbix-3
        ZBX_SERVER_ID: 3
      ports:
        - "10051"
      networks:
        zabbix:
          aliases:
            - zabbix-3
networks:
  zabbix:
    external:
      name: zabbix       
        