version: "3.5"
services:
  zabbix-mysql:
    build:
      context: ./build
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      MYSQL_ROOT_PASSWORD: zabbix
      MYSQL_ROOT_PASSWORD: zabbix
    networks:
        zabbix:
            aliases:
            - mysql-server
    ports:
        - "3306:3306" 
    volumes:
        - data:/var/lib/mysql
networks:
  zabbix:
    external:
      name: zabbix 

volumes:
  data: