name: Create db schemas
on: workflow_dispatch

jobs:
  build-db-schema:
    runs-on: ubuntu-22.04
    steps:
    - name: Install apt package for build
      run: |
        sudo apt-get update
        sudo apt-get --ignore-missing install -y build-essential cmake libgmp3-dev gengetopt libpcap-dev flex byacc libjson-c-dev pkg-config libunistring-dev dpkg-dev devscripts wget git gcc automake dh-make build-essential autoconf autotools-dev quilt pkg-config libsnmp-dev libpq-dev libsqlite3-dev libcurl4-openssl-dev libldap2-dev libiksemel-dev libopenipmi-dev libssh2-1-dev unixodbc-dev default-jdk libxml2-dev libpcre3-dev libevent-dev curl libssl-dev

    - name: Build database schemas and upload to s3
      run: |
        git clone https://gitlab.com/mikler/glaber.git
        cd glaber
        git checkout tags/2.8.1
        export GLABER_VERSION=`cat include/version.h | grep "GLABER_VERSION" | grep -Po "(\d+\.\d+\.\d+)"`
        export AWS_ACCESS_KEY_ID=${{ secrets.S3_UPLOAD_USER }}
        export AWS_SECRET_ACCESS_KEY=${{ secrets.S3_UPLOAD_PASS }}
        export AWS_DEFAULT_REGION=ru-central1
        ./bootstrap.sh
        ./configure
        make dbschema gettext
        cd database/mysql/
        cat schema.sql > create.sql
        cat images.sql >> create.sql
        cat data.sql >> create.sql
        tar -czvf $GLABER_VERSION-create-mysql.sql.tar.gz create.sql
        aws s3 --endpoint-url=https://storage.yandexcloud.net \
            cp $GLABER_VERSION-create-mysql.sql.tar.gz s3://glaber/repo/
        touch  index.html
        OBJECTS=$(aws s3 --endpoint-url=https://storage.yandexcloud.net \
            ls s3://glaber/repo/ | awk '{print $4}')
        for i in $OBJECTS; do echo '<a href="./repo/'$i'">'$i'</a><br>' >> index.html;done
        aws s3 --endpoint-url=https://storage.yandexcloud.net \
            cp index.html s3://glaber
