name: Docker Image CI build docker
on:
  push:
    branches:
    - 'build/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build glaber-server image
      run: |
        BASE_IMAGE="$REGISTRY/$GITHUB_REPOSITORY/$PACKAGE"
        GLABER_BUILD_VERSION=$(cat glaber.version)
        GLABER_SERVER_LATEST=$BASE_IMAGE:latest
        GLABER_SERVER_VERSION=$BASE_IMAGE:$GLABER_BUILD_VERSION
        docker login $REGISTRY --username $GITHUB_ACTOR --password ${{ secrets.GITHUB_TOKEN }}
        cd glaber-server
        docker build . -t $GLABER_SERVER_LATEST
        docker tag $GLABER_SERVER_LATEST $GLABER_SERVER_VERSION
        docker push $GLABER_SERVER_LATEST
        docker push $GLABER_SERVER_VERSION
      env:
        REGISTRY: docker.pkg.github.com
        PACKAGE: glaber-server

    - name: Build glaber-nginx image
      run: |
        BASE_IMAGE="$REGISTRY/$GITHUB_REPOSITORY/$PACKAGE"
        GLABER_BUILD_VERSION=$(cat glaber.version)
        GLABER_NGINX_LATEST=$BASE_IMAGE:latest
        GLABER_NGINX_VERSION=$BASE_IMAGE:$GLABER_BUILD_VERSION
        docker login $REGISTRY --username $GITHUB_ACTOR --password ${{ secrets.GITHUB_TOKEN }}
        cd glaber-nginx
        docker build . -t $GLABER_NGINX_LATEST
        docker tag $GLABER_NGINX_LATEST $GLABER_NGINX_VERSION
        docker push $GLABER_NGINX_LATEST
        docker push $GLABER_NGINX_VERSION
      env:
        REGISTRY: docker.pkg.github.com
        PACKAGE: glaber-nginx