name: Create mysql db schema
on:
  push:
    branches:
    - 'feature/make-upload-database-shema-to-s3'
jobs:
  build-db-schema:
    runs-on: ubuntu-22.04
    steps:
    - name: Install apt packege for build
      run: |
        sudo apt-get update
        sudo apt-get --ignore-missing install -y sshpass build-essential cmake libgmp3-dev gengetopt libpcap-dev flex byacc libjson-c-dev pkg-config libunistring-dev dpkg-dev devscripts wget git gcc automake dh-make build-essential autoconf autotools-dev quilt pkg-config libsnmp-dev libpq-dev libsqlite3-dev libcurl4-openssl-dev libldap2-dev libiksemel-dev libopenipmi-dev libssh2-1-dev unixodbc-dev default-jdk libxml2-dev libpcre3-dev libevent-dev curl libssl-dev

    - name: Build database schema and upload to s3
      run: |
        git clone https://gitlab.com/mikler/glaber.git
        cd glaber
        export GLABER_VERSION=`cat include/version.h | grep "GLABER_VERSION" | grep -Po "(\d+\.\d+\.\d+)"`
        ./bootstrap.sh
        ./configure
        make dbschema gettext
        wget https://dl.min.io/client/mc/release/linux-amd64/mc
        chmod +x mc
        mv mc /usr/local/bin
        mc alias set glaber https://storage.yandexcloud.net \
           ${{ secrets.S3_UPLOAD_USER }} \
           ${{ secrets.S3_UPLOAD_PASS }}
        cd database/mysql/
        cat schema.sql > create.sql
        cat images.sql >> create.sql
        cat data.sql >> create.sql
        tar -czvf $GLABER_VERSION-create.sql.tar.gz create.sql
        mc cp $GLABER_VERSION-mysql-create.sql.tar.gz glaber:/


