name: Docker build images with packer
on:
  push:
    branches:
    - 'packer/**'
  schedule:
    - cron: '0 4 * * *'
jobs:
  packer:
    runs-on: ubuntu-22.04
    name: Run Packer docker build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare variables
        run: |
          GLABER_TAG=$(git ls-remote --refs --sort='version:refname' --tags \
                      https://gitlab.com/mikler/glaber.git origin '2.*' | \
                      tail --lines=1 | cut --delimiter='/' --fields=3)
          GLABER_VERSION=$(curl -s https://gitlab.com/mikler/glaber/-/raw/${GLABER_TAG}/include/version.h | \
                          grep GLABER_VERSION | tr -dc 0-9.)
          docker manifest inspect ghcr.io/bakaut/glaber/glaber-server:$GLABER_VERSION-pkr 1>/dev/null && \
          echo "IMAGE=exist" >> $GITHUB_ENV
          echo "GLABER_VERSION=$GLABER_VERSION" >> $GITHUB_ENV
          echo "TMG_TAG=$GLABER_VERSION-pkr-temp" >> $GITHUB_ENV
          echo "REGISTRY=ghcr.io" >> $GITHUB_ENV
          echo "DOCKER_USERNAME=$GITHUB_ACTOR" >> $GITHUB_ENV

      - name: Setup `packer`
        if: ${{ env.IMAGE != 'exist' }}
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "1.8.5"

      - name: Run `packer init`
        if: ${{ env.IMAGE != 'exist' }}
        id: init
        run: |
          export PACKER_GITHUB_API_TOKEN=${{ secrets.PACKER_TOKEN }}
          cd .github/workflows/build/docker
          packer init .

      - name: Run `packer validate`
        if: ${{ env.IMAGE != 'exist' }}
        id: validate
        run: |
          cd .github/workflows/build/docker
          packer validate .

      - name: Run `packer build`
        id: build
        run: |
          export DOCKER_PASSWORD=${{ secrets.GITHUB_TOKEN }}
          cd .github/workflows/build/docker
          packer build -var "tag_version=-pkr-temp" \
                 -color=false -timestamp-ui \
                 -warn-on-undeclared-var .

      - name: Testing glaber server start
        if: ${{ env.IMAGE != 'exist' }}
        id: test
        run: |
          export GLABER_VERSION=$TMG_TAG
          ./glaber.sh start

      - name: Run `packer release`
        if: ${{ env.IMAGE != 'exist' }}
        id: release
        run: |
          export DOCKER_PASSWORD=${{ secrets.GITHUB_TOKEN }}
          cd .github/workflows/build/docker
          packer build -color=false -timestamp-ui \
                 -warn-on-undeclared-var .
